frameWorkProje/Models/CallLogViewModel.cs
using EntityLayer.Concreate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace frameWorkProje.Models
{
    public class CallLogViewModel
    {
        public CallLog Calllog { get; set; }
        public Job Job { get; set; }

    }
}

frameWorkProje/Controllers/CallLogController.cs
using BusinessLayer.Concreate;
using DataAccessLayer.Concreate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concreate;
using frameWorkProje.Models;
using frameWorkProje.Singleton;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace frameWorkProje.Controllers
{

    public class CallLogController : Controller
    {
        CallLogManager callLogManager = new CallLogManager(new EfCallLogRepository());
        JobManager jm = new JobManager(new EfJobRepository());

        // GET: CallLog
        public ActionResult Index(int id = 0, int persoId = 0)
        {
            if (id <= 0 || persoId <= 0)
            {
                return RedirectToAction("Index", "Home");
            }

            // burada cagri idyi aliıp o cagri id kayıtlı iş çekip iş sonlansın mı diye sorluacak
            int cagriId = id;
            Job jobModel = jm.GetByFilter(x => x.CallLogId == cagriId);// ilgili cagri modelini de gönderecez bunun için viewmodel kullanıcaz
            if (jobModel != null)
            {
                ViewData["jobId"] = jobModel.JobId;
                ViewData["jobDesc"] = jobModel.JobDescription;
                ViewData["JobMethods"] = jobModel.JobMethods;
                ViewData["isImportant"] = jobModel.IsImportant;
                ViewData["creatingTime"] = jobModel.CreatingTime;
                ViewData["updatingTime"] = jobModel.UpdatingTime;
                ViewData["isOlusturan"] = jobModel.User.UserName;
            }
            else
            {
                ViewBag.listele = "listele";
            }


            var model = new CallLog();

            if (FrameWorkProjeSingleton.Instance.isAdmin())
            {
                model = callLogManager.GetById(cagriId);// admin ise tüm çağrılara giribilri demektir.
            }
            else
            {
                var jobList = jm.GetJobWithfilter( false, FrameWorkProjeSingleton.Instance.currentUSer.UserName);
                foreach (var item in jobList)
                {
                    if (item.UserId == persoId && item.CallLogId == cagriId)
                    {
                        model = callLogManager.GetById(cagriId);
                        return View(model);
                    }

                }
                return RedirectToAction("Index", "Home");// personel ise tüm herkesin cagrılarına gidemez.     
            }

            return View(model);



        }
        [HttpPost]
        public ActionResult Index(CallLog call)
        {
            // veri geliyor
            var updaet = callLogManager.GetById(call.CallLogId);
            updaet.CallLogDesc = call.CallLogDesc;// çağrı durumunu false yaparsa otomatik işte silinecek 
            updaet.UpdatingTime = DateTime.Now;
            callLogManager.CallLogUpdate(updaet);


            return RedirectToAction("Index", "CallLog", new { id = call.CallLogId, persoId = FrameWorkProjeSingleton.Instance.currentUSer.UserId });
        }

        [Authorize(Roles = "admin")]
        public ActionResult Cagrilar(int id = 0)
        {
            Context c = new Context();
            var callogList = new List<CallLog>();


            callogList = (from call in c.CallLogs
                          join cust in c.Customers
                          on call.CustomerId equals cust.CustomerId
                          where (call.CustomerId == id)
                          select call
                              ).ToList();

            ViewBag.userId = Singleton.FrameWorkProjeSingleton.Instance.currentUSer.UserId;
            return View(callogList);
        }

    }
}

frameWorkProje/Controllers/JobAddController.cs
using BusinessLayer.Concreate;
using DataAccessLayer.Concreate;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concreate;
using frameWorkProje.Singleton;
using System;
using System.Web.Mvc;

namespace frameWorkProje.Controllers
{
    public class JobAddController : Controller
    {
        JobManager jm = new JobManager(new EfJobRepository());
        CallLogManager cm = new CallLogManager(new EfCallLogRepository());
        public ActionResult CreateJob()
        { 
  
            var values = cm.CallLogList();

            return View(values);
        }
 
        public ActionResult JobDelete(int id)
        {
            // job status false yapılacak
            
            var jap = jm.GetByFilter(x => x.JobId == id);
            if(jap != null)
            jm.ChangeJubStatus(jap.JobId);
            return RedirectToAction("Index","Home");

        }

        [HttpPost]
        public ActionResult JobUpdate(Job job)
        {

            var jap = jm.GetByFilter(x => x.JobId == job.JobId);
            jap.JobDescription = job.JobDescription;
            jap.JobMethods = job.JobMethods;
            jap.UpdatingTime = DateTime.Now;
            jap.IsImportant = Convert.ToBoolean(job.IsImportant);

            // iş durumu false olacak

            jm.JobUpdate(jap);

            return RedirectToAction("Index", "CallLog", new { id = jap.CallLogId, persoId = FrameWorkProjeSingleton.Instance.currentUSer.UserId });
      
        }

        [HttpPost]
        public ActionResult CreateJob(Job job)// 
        {
       
            if (job.CallLogId == 0)
            {
                // çagrı seçmemiş demektir
                // js ile kontrol ediliyor zaten burasıda 2. kontrol yeri
            } 
            
            else
            {

                using (var db = new Context())
                {
                    var user = cm.GetCallWithFilter(x => x.CallLogId == job.CallLogId);
                    user.CallLogStatus = false;// cagri durumu false oluyor böylece yanıtlanmıs demek
                    cm.CallLogUpdate(user);
                    // daha sonra job ekleniyor 
                    DateTime date = DateTime.Now;
                    var shortDate = date.Date;
                    job.CreatingTime = shortDate;
                    job.UpdatingTime = shortDate;
                    job.JobStatus = "aktif";

                    job.UserId = FrameWorkProjeSingleton.Instance.currentUSer.UserId;// personel id giren kişi çekilece


                    jm.JobAdd(job);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

frameWorkProje/Views/CallLog/Cagrilar.cshtml
@using EntityLayer.Concreate
@model List<CallLog>
@{
    var x = ViewBag.userId;
    ViewBag.Title = "Cagrilar";
}
@if (Model.Count > 0)
{
    foreach (var item in Model)
    {
        <a class="headerDesign">@item.Customer.CustomerName MÜŞTERİSİNİN KAYITLARI </a>
    }
    <table class="table customTable">
        <thead class="thead-dark">
            <tr>

                <th> Çağrı Numarası</th>
                <th> Çağrı Açıklaması</th>
                <th> Çağrı Durumu</th>
                <th> Çağrı Olusturma Zamanı</th>
                <th width="300px"> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td> @item.CalllNumber </td>
                    <td> @item.CallLogDesc </td>
                    <td> @item.CallLogStatus </td>
                    <td> @item.CreatingTime </td>
                    <td>  <a class="btn btn-outline-success my-2 my-sm-0" href="/CallLog/Index/@item.CallLogId?persoId=@x">Detay</a> </td>

                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <br />
    <a class="headerDesign">Bu müşteri hiç çağrı oluşturmamış</a>
}

frameWorkProje/Views/CallLog/Index.cshtml
@model EntityLayer.Concreate.CallLog

@{
    ViewBag.Title = "Index";

    var ya = Model.CallLogStatus.Value;
    var za = !ya;

    var onemli = true;
    var onemliDe = false;
    var jobId = 1;

    if (ViewBag.listele != "listele")
    {
        var onemliS = ViewData["isImportant"].ToString();
        if (onemliS == "True")
        {
            onemli = true;
            onemliDe = !onemli;

        }
        else if (onemliS == "False")
        {
            onemli = false;
            onemliDe = !onemli;
        }
        jobId = Convert.ToInt32(ViewData["jobId"].ToString());

    }




}

<a class="headerDesign" style="font-size:72px">ÇAĞRI DETAY SAYFASI</a>
@if (Model == null)
{
    <h1>@ViewBag.hata</h1>

}

else
{
    <h2>ÇAĞRI BİLGİLERİ</h2>

    <table class="table">
        <tr>
            <th style="display:none">

                ÇAĞRI ID
            </th>
            <th>
                MÜŞTERİ ADI
            </th>
            <th>
                ÇAĞRI AÇIKLAMASI
            </th>
            <th>
                ÇAĞRI DURUMU
            </th>
            <th>
                ÇAĞRI OLUŞTURMA ZAMANI
            </th>
            <th>
                ÇAĞRU SON GUNCELLEME ZAMANI
            </th>
            <th>
                ÇAĞRU NUMARASI
            </th>
            <th>GUNCELLE</th>
        </tr>


        @using (Html.BeginForm("Index", "CallLog", FormMethod.Post))
        {


            <tr>
                <td style="display:none">
                    @Html.TextBoxFor(c => c.CallLogId, new { @readonly = true })
                </td>
                <td>
                    @Html.TextBoxFor(c => c.Customer.CustomerName, new { @readonly = true })
                </td>
                <td>
                    @Html.TextBoxFor(c => c.CallLogDesc)
                </td>
                <td>
                    <select name="CallLogStatus" disabled>
                        <option value="@ya">
                            @ya
                        </option>
                        <option value="@za">
                            @za
                        </option>

                    </select>
                <td>
                    @Html.TextBoxFor(c => c.CreatingTime, new { @readonly = true })
                </td>
                <td>
                    @Html.TextBoxFor(c => c.UpdatingTime, new { @readonly = true })
                </td>
                <td>
                    @Html.TextBoxFor(c => c.CalllNumber, new { @readonly = true })
                </td>
                <td>
                    <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Güncelle</button>
                </td>
            </tr>

        }




    </table>



   
    <br />

    if (ViewBag.listele != "listele")
    {
        <h2> BU ÇAĞRIYA SAHİP İŞ </h2>

        <table class="table">
            <tr>
                <th style="display:none">
                    İŞ İD
                </th>
                <th>
                    İŞ AÇIKLAMASI
                </th>
                <th>
                    İŞ ÇÖZME YÖNTEMLERİ
                </th>
                <th>
                    ÖNEMLİ Mİ?
                </th>

                <th>
                    OLUŞTURMA ZAMANI
                </th>
                <th>
                    SON GUNCELLEME ZAMANI
                </th>
                <th>
                    OLUŞTURAN PERSONEL
                </th>
                <th>GUNCELLE/KALDIR</th>
            </tr>


            @using (Html.BeginForm("JobUpdate", "JobAdd", FormMethod.Post))
            {
                <tr>
                    <td style="display:none">
                        <input type="text" value="@ViewData["jobId"]" name="JobId" />
                    </td>
                    <td>
                        <input type="text" value="@ViewData["jobDesc"]" name="JobDescription" />
                    </td>
                    <td>
                        <input type="text" value="@ViewData["JobMethods"]" name="JobMethods" />
                    </td>
                    <td>
                        <select name="IsImportant">
                            <option value="@onemli.ToString()">
                                @onemli
                            </option>
                            <option value="@onemliDe.ToString()">
                                @onemliDe
                            </option>
                        </select>
                    </td>


                    <td>
                        <input type="text" value="@ViewData["creatingTime"]" name="creatingTime" readonly />
                    </td>
                    <td>
                        <input type="text" value="@ViewData["updatingTime"]" name="updatingTime" readonly />
                    </td>
                    <td>
                        <input type="text" value="@ViewData["isOlusturan"]" readonly />
                    </td>
                    <td>
                        <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">Güncelle</button>
                        <a class="btn btn-outline-danger my-2 my-sm-0" href="/JobAdd/JobDelete/@jobId">Kaldır</a>

                    </td>
                </tr>

            }

        </table>
    }



}